# Description : dummy service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-service
  #namespace: movies-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-service
  template:
    metadata:
      labels:
        app: movies-service
    spec:
      containers:
        - name: movies-service
          image: hari5115/pg-test:v2
          ports:
            - containerPort: 3000
          env:
            - name: DB_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_CONNECTION
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_PASS
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_HOST
          imagePullPolicy: Always

        # cloud SQL proxy container as side car container 
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.28.0
          command:
            - "/cloud_sql_proxy"
            - "-instances=sandbox-db-enablers:us-central1:sqlpostgre5=tcp:0.0.0.0:5432"
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              memory: "2Gi"
              cpu:    "1"
      serviceAccountName: movies-ksa
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
